### ISSUE TITLE
Change image URI when using the convert effect in coloractions submodule.

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/image_effects#16] opened 2022-08-26 15:14 UTC
Currently the action to convert image formats in the Coloractions submodule works for the conversion but can't actually change the filename. As described in the comments in the code:

> If you've been using transparencies in the process, the result may get saved as a PNG (as the image was treated as a one in in-between processes). If this is not desired (file sizes may get too big) you should use this process to force a flatten action before saving. **For technical reasons, changing the file format within imagecache does not change the filename suffix. A png may be saved as a .jpg or vice versa. This may confuse some browsers and image software, but most of them have no trouble**. 

I've tried using `hook_file_url_alter` to change things but the approach I've tried ended up with broken URLs due to double encoding (I was trying to pass the original extension via a query parameter in the URL, which gets garbled). However, if we are allowed to alter the URL after it's generated I think perhaps we can avoid the double encoding.

See: 

 -  Allow altering image style urls [#5745 ](https://github.com/backdrop/backdrop-issues/issues/5745)

**Comment by laryn** [comment] 2022-08-26 15:50
I temporarily saved the attempt from earlier in this branch: https://github.com/laryn/image_effects/tree/1.x-1.x-issue-16

Again, the work in that branch is based on Vincent Demer's work -- with big help from @indigoxela.

**Comment by indigoxela** [comment] 2022-08-27 09:43
Hm... didn't actually look closer, but ... how do CDN modules do that?

Could rewriting to a http(s) scheme or a full path (without stream wrapper) in hook_file_url_alter help? As far as I can see, [file_create_url](https://docs.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_create_url/1) wouldn't encode that.

**Comment by laryn** [comment] 2022-09-08 14:37
Great idea! Are you willing to test this PR @indigoxela?
https://github.com/backdrop-contrib/image_effects/pull/17

**Comment by indigoxela** [comment] 2022-09-09 07:20
We're getting closer! :tada: Many thanks for all your work on this!

There are still some things to fix, though:

When creating the image style, the default (demo) image can't get converted.
Looking at the image url explains it:

```
http://.../files/styles/footest_webp/public/core/modules/image/images/sample.webp?orig=png?cache_bypass=1662707108
```
Note the double `?` caused by the `cache_bypass`.

When adding an image to a node, the thumbnail creation causes Notices:
```
Notice: Undefined index: orig in image_effects_coloractions_image_style_deliver() (line 981 of .../modules/image_effects/coloractions/image_effects_coloractions.module).
```
The thumbnail still uses (and should use) the original extension.

Now a trickier problem. By accident I used an 8-bit color png, which causes:
```
Warning: imagewebp(): Palette image not supported by webp in image_gd_save() (line 280 of .../core/modules/system/image.gd.inc). 
```

Out of curiosity I also tried a gif, which after node, save again shows:

```
Notice: Undefined index: orig in image_effects_coloractions_image_style_deliver() (line 980 of .../modules/image_effects/coloractions/image_effects_coloractions.module).
```
I belief, most of all that can be fixed by defensive coding. Not sure about the default "sample.png" when creating the style.

**Comment by indigoxela** [comment] 2022-09-09 07:27
Re the palette images (8-bit png, gif) the recommendation in the web seems to be to use `imagepalettetotruecolor` as an intermediate step (convert to 24bit before converting to webp).

**Comment by indigoxela** [comment] 2022-09-09 07:31
Another finding with the default sample.png:

```
Source image at public://core/modules/image/images/sample.png not found while trying to generate derivative image at public://styles/footest_webp/public/core/modules/image/images/sample.webp.
```
That "public://" seems to be the culprit here (besides the broken `?...?` url).

**Comment by laryn** [comment] 2022-09-20 18:13
@indigoxela I adjusted somewhat with more defensive coding on the `orig` query parameter, and a bit of hackishness to avoid the preview image (it converts that image to webp but doesn't change the extension for that one image only... hacky for sure and I'm open to other ideas...). I can't seem to replicate the other error about palette image not being supported. Do you have a sample image that causes that which can be shared?

**Comment by laryn** [comment] 2022-09-20 18:15
Also, does that happen if you convert to or from other formats? Maybe it's a separate issue if it's not webp specific.

**Comment by indigoxela** [comment] 2022-09-21 06:36
> I can't seem to replicate the other error about palette image not being supported. Do you have a sample image that causes that which can be shared?

That's easy. PNG images as they get created by devel_generate are palette images. If you happen to have ImageMagick installed, you can verify with `identify -verbose YOURIMAGE.png|grep Type`.

Visiting a generated node with such a palette image triggers the warning, and the image won't show. Inspecting the files directory shows that an empty (zero byte) file gets created (YOURIMAGE.webp). That's reproducible.

**Comment by indigoxela** [comment] 2022-09-21 06:41
Two sample palette PNG images, one created with GD (by devel_generate) one created with Gimp:

![palette-devel_gen](https://user-images.githubusercontent.com/842066/191432453-04f33bb4-b12f-45d4-b11c-0d94f34f6acc.png)

![palette-gimp](https://user-images.githubusercontent.com/842066/191432499-7b577aa9-1f68-476a-80c8-9bbf8679c2bc.png)

(I hope, GitHub doesn't process them on upload...)

**Comment by laryn** [comment] 2022-09-26 15:52
@indigoxela I downloaded the first image and uploaded it into a node. The image style that converts to `.webp` didn't seem to have a problem with it (the converted image displays and I don't see a warning in the watchdog), and when I verify that it's still a palette image, it does seem to be:

> identify -verbose 191432453-04f33bb4-b12f-45d4-b11c-0d94f34f6acc.png|grep Type
>  Type: Palette

The only issue I'm seeing is that the color conversion is pretty bad. (The second image comes out as grey, for example). Maybe `imagepalettetotruecolor` will help with that.

**Comment by indigoxela** [comment] 2022-09-27 06:50
> (the converted image displays and I don't see a warning in the watchdog), and when I verify that it's still a palette image, it does seem to be

Interesting... let's compare our setups:

- My effect only converts the type, nothing else (Change file format Convert to: webp)
- PHP 7.4.30 (with php-fpm)
- GD 2.3.3 with WebP support enabled

Turning that effect on for post, go to a node with a palette image - broken. Deleted all those effect images to make sure it's not a problem from a previous (unsuccessful) conversion, visit node again. Same problem. Reproducible.

Same message again:
```
Warning: imagewebp(): Palette image not supported by webp in image_gd_save() (line 280 of ...core/modules/system/image.gd.inc).
```
@laryn does that help to narrow down the cause?

> The second image comes out as grey, for example...

Color shifts aren't what we want, for sure.

**Comment by laryn** [comment] 2022-10-10 19:48
@indigoxela Can you test the latest? (As an aside, I saw a notice on the PHP website about changes with PHP 8 when I was looking into `imagepalettetotruecolor`; filed separately https://github.com/backdrop-contrib/image_effects/issues/18)

**Comment by indigoxela** [comment] 2022-10-13 07:25
This works like a charm! :tada: 

Tested with both, a palette png and a gif - both get properly converted to webp without color shift.

One thing came to my mind - I only test the conversion, no other effect applied to my check. Maybe you had trouble to reproduce my problems with palette images, because you added other effects, like resizing?

Anyway - I think you nailed it.

One question: I'm assuming, this effect gets moved out of the "Color actions" to a more appropriate place. It's hard to find it there.

**Comment by laryn** [comment] 2022-10-13 18:01
Thanks @indigoxela -- given your tests and my own I feel pretty good about this. I'll give @stpaultim another day or so to weigh in if he wants (but no pressure if he can't squeeze it in).

**Comment by laryn** [comment] 2022-10-14 17:08
Thanks @indigoxela -- merged!

I'll probably wait until https://github.com/backdrop-contrib/image_effects/issues/19 is complete before releasing a new version.

**Closed as completed** 2022-10-14 17:07 UTC
